# version: '3.8'

x-airflow-common: &airflow-common
  #image: apache/airflow:2.8.1
  build: .
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres_airflow/airflow_db # mai check lai cho nay
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    #DW_CONN_STRING: postgresql+psycopg2://user:password@postgres_dw:5432/fin_etl_db
    #_PIP_ADDITIONAL_REQUIREMENTS: "scikit-learn pandas numpy psycopg2-binary"
    AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
    AIRFLOW__SMTP__SMTP_STARTTLS: "True"
    AIRFLOW__SMTP__SMTP_SSL: "False"
    AIRFLOW__SMTP__SMTP_USER: "trunghieu17062001@gmail.com" # Email gửi đi
    AIRFLOW__SMTP__SMTP_PASSWORD: "yhuv jixe bppf ivdj" # MẬT KHẨU ỨNG DỤNG (App Password)
    AIRFLOW__SMTP__SMTP_PORT: 587
    AIRFLOW__SMTP__SMTP_MAIL_FROM: "trunghieu17062001@gmail.com"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./logs:/opt/airflow/logs
    - ./data:/opt/airflow/data # đọc thư mục data lưu file csv
  user: "${AIRFLOW_UID:-50000}:0"

services:

  postgres_airflow:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: airflow_db
    ports:
      - "5436:5432" # đổi port local trên máy
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8079:8080"
    restart: always
    depends_on:
      - postgres_airflow
      - airflow-init
    extra_hosts:
      - "host.docker.internal:host-gateway"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    depends_on:
      - postgres_airflow
      - airflow-init
    extra_hosts:
      - "host.docker.internal:host-gateway"

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db upgrade && airflow users create \
      --username admin \
      --password admin \
      --firstname admin \
      --lastname admin \
      --role Admin \
      --email admin@example.com"
    user: "0:0"
    depends_on:
      - postgres_airflow
    extra_hosts:
      - "host.docker.internal:host-gateway"
