FROM apache/airflow:2.8.1

USER root
RUN apt-get update && apt-get install -y libpq-dev gcc

USER airflow
RUN pip install --no-cache-dir \
    scikit-learn \
    pandas \
    numpy \
    psycopg2-binary \
    matplotlib \
    seaborn \
    python-pptx